### ISSUE TITLE
About the training scenes

### ISSUE THREAD

**Issue by JiaxiongQ** [y-zheng18/HyFluid#1]
I tried to use your code reconstruct the pinf's 'sphere' scene and my synthesized scenes, and found that your model only renders the white background and noise, but not smoke. I have converted each scene into the grayscale format.
What the reason could be?  Does the background color have to be black?

**Comment by y-zheng18** [comment]
Hi, current code assumes a black background. But I think it should work if you change the background color in the volume rendering function, similar to https://github.com/bmild/nerf/blob/master/run_nerf.py#L160

**Comment by JiaxiongQ** [comment]
I close this issue.Thanks for your great work!
