### ISSUE TITLE
Some "hyperparameters" used in run_future_pred

### ISSUE THREAD

**Issue by chenwydj** [y-zheng18/HyFluid#3]
Thanks for this great work!

May I ask for the rationale behind the following "hyperparameters" used in [`run_future_pred`](https://github.com/y-zheng18/HyFluid/blob/main/utils.py#L459)?

```python
starting_frame = 89
n_pred = 30
source_height = 0.25 # which is used to build "mask_to_sim" later
```

Thank you very much!

**Comment by y-zheng18** [comment]
In future predictions, we consider the velocity field at a certain frame (89th frame here) and evolve itself to compute the future velocity fields (30 frames here), thus simulating future density. We suppose the bottom 25% height of the fluid is the source as observed in the videos and we don't simulate the source part, since it doesn't follow conservation of mass and density.

**Comment by chenwydj** [comment]
> In future predictions, we consider the velocity field at a certain frame (89th frame here) and evolve itself to compute the future velocity fields (30 frames here), thus simulating future density. We suppose the bottom 25% height of the fluid is the source as observed in the videos and we don't simulate the source part, since it doesn't follow conservation of mass and density.

Thanks for your quick reply!

My question was, how did you choose those values 89 and 30, instead of others?

```python
starting_frame = 89
n_pred = 30
```

**Comment by y-zheng18** [comment]
We use 120-frame videos so we choose the last 30 frames to evaluate future predictions :)

**Comment by chenwydj** [comment]
> We use 120-frame videos so we choose the last 30 frames to evaluate future predictions :)

Thanks!

And why using `starting_frame = 89` instead of any earlier or later frame to start?

**Comment by y-zheng18** [comment]
That's just a choice, using ```starting_frame = 89``` means the rest 30 frames are used for evaluation (about 1/4 of the video).

**Comment by chenwydj** [comment]
Thank you very much!!
