### ISSUE TITLE
How to interpret loss values

### ISSUE THREAD

**Issue by chenwydj** [y-zheng18/HyFluid#6]
Thanks for the great work and code release! It runs very smoothly.

May I ask how to interpret the loss values of each experiment?
Specifically, I suppose these results should (roughly) match Table 1. But I see some differences.

Thank you very much!

1. Reconstruct the density field
```
Avg PSNR over Test set:  31.627617955207825
Avg LPIPS over Test set:  0.09003627977023522
Avg SSIM over Test set:  0.942078793545564
```

2. Jointly reconstruct the velocity and density field
```
Avg PSNR over full simulation:  29.98221331834793
Avg SSIM over full simulation:  0.9310505782564481
Avg LPIPS over full simulation:  0.10198990033629039
[TRAIN] Iter: 100000 Rec Loss:0.00021 PSNR:37.42 Flow Loss: 0.35, U loss: 0, V loss: 0, W loss: 0, d loss: 0, proj Loss:0.0014, den2vel loss:0.074, Vel Loss: 2.8
```

3. Add vortex particles and optimize physical parameters
```
Avg PSNR over full simulation:  29.981229345003765
Avg SSIM over full simulation:  0.9315193340182304
Avg LPIPS over full simulation:  0.10126748938734333
[TRAIN] Iter: 10000 PSNR:37.24 Flow Loss: 0.41, Vort Loss: 0.0094, Total intense: 4.902728080749512, Total r: 0.6438688039779663
```

4. Re-simulate
```
Avg PSNR over full simulation:  29.954852958520252
Avg SSIM over full simulation:  0.9308862949411074
Avg LPIPS over full simulation:  0.1018367561356475
```

5. Predict the future
```
Avg PSNR over full simulation:  27.5642937819163
Avg SSIM over full simulation:  0.8920999685923259
Avg LPIPS over full simulation:  0.16299138069152833
```

**Comment by y-zheng18** [comment]
Hi, 

The results look fine to me. Are the numbers the average from several seqs? 

The flow loss enforces the velocity field to evolve the density field (e.g., change of density should be intrigued by the velocity), the projection loss describes how the velocity field follows mass conservation law. You can refer to the paper for more details.

**Comment by chenwydj** [comment]
Thanks @y-zheng18!

1. They came from one sequential run of commands in [readme](https://github.com/y-zheng18/HyFluid?tab=readme-ov-file#quick-start).
2. For the column "Novel view synthesis" in Table 1, does it correspond to the 3rd block "Add vortex particles and optimize physical parameters" I pasted above?
3. Why do results of the 2nd~5th blocks above come from the "full simulation" instead of test frames (beyond 120 frames) like the 1st block?

Thank you!

**Comment by y-zheng18** [comment]
For 2, the novel view synthesis results in tab 1 correspond to the 1st block, which only shows the quality of density reconstruction. For 3, "full simulation" means we use the reconstructed velocity field to evolve the density field from a start frame, such that we can evaluate the accuracy of the reconstructed velocity field. The full simulation results are also from the test novel view.

**Comment by chenwydj** [comment]
Thanks for the quick reply!!
